### ISSUE TITLE
Getting error about string argument without encoding when writing a CSV reader

### ISSUE THREAD

**Issue by kszlim** [nautechsystems/nautilus_trader#563]
Was testing out develop branch due needing this change https://github.com/nautechsystems/nautilus_trader/pull/558

```
chunks = tuple([dict(zip(self.header, line.split(bytes(self.separator)))) for line in process.split(b"\n")])  # type: ignore
TypeError: string argument without an encoding
```

This was specifically when using a `CSVReader` with `chunked=False` and `as_dataframe=False`

https://github.com/nautechsystems/nautilus_trader/blob/dac7a280c52ddcf634d2cd6e11c9ad628d933852/nautilus_trader/persistence/external/readers.py#L282

This line breaks due to missing string encoding in the `bytes` function.

**Comment by cjdsellers** [comment]
Hi @kszlim thanks for reporting this!

We'll look into it as soon as we can, bandwidth dependent. Hopefully this week though.

**Comment by cjdsellers** [comment]
Fixed from #593 
Many thanks to @limx0 :rocket:

**Comment by 772435284** [comment]
I think it is not fixed, I still get the error when running the code in https://docs.nautilustrader.io/user_guide/loading_external_data.html
This line should be changed to `chunks = tuple([dict(zip(self.header, line.split(bytes(self.separator,encoding='utf8')))) for line in process.split(b"\n")])  # type: ignore`
